name: Scamp
options:
  minimumXcodeGenVersion: 2.30.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.scamp.player
    MACOSX_DEPLOYMENT_TARGET: 26.0
targets:
  Scamp:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/Scamp
      - path: App/Assets.xcassets
        buildPhase: resources
    info:
      path: App/Info.plist
    settings:
      base:
        PRODUCT_NAME: Scamp
        SWIFT_VERSION: 6.0
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: App/Scamp.entitlements
